### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by mithrandi**
This just bumps all the dependencies to latest. The tests pass, and it seems to work.

---

This change is [Reviewable](https://reviewable.io/reviews/jonathanj/clj-codetip/13)

### CODE REVIEW

**Comment by jonathanj** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/jonathanj/clj-codetip/13)_

**Comment by jonathanj** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[project.clj, line 21 [r1]](https://reviewable.io:443/reviews/jonathanj/clj-codetip/13#-KHGw5lg0M8BNAYqZ7mj:-KHGw5lg0M8BNAYqZ7mk:-1254718063) ([raw file](https://github.com/jonathanj/clj-codetip/blob/4ff5e5dd445203374904c1d2f5471f234a9794f4/project.clj#L21)):_

> ``` Clojure
>                  [yesql "0.5.3"]
>                  [environ "1.0.3"]
>                  [joplin.core "0.3.6" :exclusions [clj-time org.clojure/java.classpath]]
> ```

https://github.com/juxt/joplin/wiki/Differences-between-0.2-and-0.3

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/jonathanj/clj-codetip/13)_

**Comment by jonathanj** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[project.clj, line 21 [r1]](https://reviewable.io:443/reviews/jonathanj/clj-codetip/13#-KHGw5lg0M8BNAYqZ7mj:-KHGwSwSCyshWnVzuake:-1664858665) ([raw file](https://github.com/jonathanj/clj-codetip/blob/4ff5e5dd445203374904c1d2f5471f234a9794f4/project.clj#L21)):_
<details><summary>

<i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary>



> https://github.com/juxt/joplin/wiki/Differences-between-0.2-and-0.3</details>
> Do any of these apply?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/jonathanj/clj-codetip/13)_

**Comment by mithrandi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[project.clj, line 21 [r1]](https://reviewable.io:443/reviews/jonathanj/clj-codetip/13#-KHGw5lg0M8BNAYqZ7mj:-KHQESeLULCH2vnL-Tv1:-2016854457) ([raw file](https://github.com/jonathanj/clj-codetip/blob/4ff5e5dd445203374904c1d2f5471f234a9794f4/project.clj#L21)):_
<details><summary>

<i>Previously, jonathanj (Jonathan Jacobs) wrote…</i></summary>



> Do any of these apply?
> </details>
> Hmm, I guess a bunch of them apply, although weirdly it doesn't seem to have broken anything. I'll change stuff anyway.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/jonathanj/clj-codetip/13)_

**Comment by mithrandi** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[project.clj, line 21 [r1]](https://reviewable.io:443/reviews/jonathanj/clj-codetip/13#-KHGw5lg0M8BNAYqZ7mj:-KHQjSBmC3_-pjigoQ86:-2108041165) ([raw file](https://github.com/jonathanj/clj-codetip/blob/4ff5e5dd445203374904c1d2f5471f234a9794f4/project.clj#L21)):_
<details><summary>

<i>Previously, mithrandi (Tristan Seligmann) wrote…</i></summary>



> Hmm, I guess a bunch of them apply, although weirdly it doesn't seem to have broken anything. I'll change stuff anyway.</details>
> Okay, I pushed more changes.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/jonathanj/clj-codetip/13)_

**Comment by jonathanj** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/jonathanj/clj-codetip/13)_

**Pull request merged**
